# Generated by Django 4.1.3 on 2023-01-18 17:34

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Category Logo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('preview_des', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('old_price', models.FloatField(blank=True, null=True, verbose_name='Product Old Price')),
                ('is_stock', models.BooleanField(default=True, verbose_name='Poduct available or not')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(choices=[('size', 'size'), ('color', 'color')], max_length=100, verbose_name='Variation Type')),
                ('name', models.CharField(max_length=100, verbose_name='Variation Name')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='If Different Price Exists ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product_gallery/', verbose_name='Gallery Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Uploding time')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Logo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Favicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo/', verbose_name='Favicon')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active Favicon')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banner Title')),
                ('short_desc', models.TextField(blank=True, max_length=250, null=True, verbose_name='Short Description')),
                ('image', models.ImageField(upload_to='banner', verbose_name='Banner Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='banner')),
            ],
        ),
    ]
