# Generated by Django 4.1.3 on 2022-11-10 07:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Category Logo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.category', verbose_name='children')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Product Name')),
                ('preview_des', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('price', models.FloatField(verbose_name='Product Price')),
                ('old_price', models.FloatField(verbose_name='Product Old Price')),
                ('is_stock', models.BooleanField(default=True, verbose_name='Poduct available or not')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created'],
            },
        ),
    ]
