# Generated by Django 4.1.3 on 2023-01-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Offer Title')),
                ('background', models.ImageField(upload_to='banner', verbose_name='Background Image')),
                ('discount', models.CharField(max_length=15, verbose_name='Discount')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='')),
            ],
        ),
    ]
