# Generated by Django 4.1.3 on 2023-01-21 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_variatin',
            field=models.CharField(blank=True, choices=[('Most View Products', 'Most View Products'), ('Recent Products', 'Recent Products'), ('Featured Products', 'Featured Products')], max_length=100, null=True, verbose_name='Product Variation'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='offer'),
        ),
    ]
