# Generated by Django 4.1.3 on 2022-11-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug_alter_product_old_price'),
        ('store', '0005_product_slug'),
    ]

    operations = [
    ]
