# Generated by Django 4.1.3 on 2022-11-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_merge_20221111_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
