# Generated by Django 4.1.3 on 2022-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='test', unique=True, verbose_name=''),
            preserve_default=False,
        ),
    ]
