# Generated by Django 4.1.3 on 2022-12-15 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_productimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation', models.CharField(choices=[('size', 'size'), ('color', 'color')], max_length=100, verbose_name='Variation Type')),
                ('name', models.CharField(max_length=100, verbose_name='Variation Name')),
                ('price', models.IntegerField(verbose_name='Variation Product Size')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='product')),
            ],
        ),
    ]
