# Generated by Django 4.1.3 on 2023-01-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='address1',
            field=models.TextField(blank=True, null=True, verbose_name='Address1'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='address2',
            field=models.TextField(blank=True, null=True, verbose_name='Address2'),
        ),
    ]
