# Generated by Django 4.1.3 on 2023-01-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Notification Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('userobj', models.ManyToManyField(blank=True, to='notification.userobj', verbose_name='notification')),
            ],
        ),
    ]
