# Generated by Django 4.1.3 on 2023-01-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_userobj_created_alter_userobj_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userobj',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserObj',
        ),
    ]
