# Generated by Django 4.1.3 on 2023-01-18 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('user_name', models.CharField(max_length=150, unique=True, verbose_name='User Name')),
                ('user_type', models.CharField(choices=[('visitor', 'visitor'), ('owner', 'owner'), ('admin', 'admin'), ('manager', 'manager'), ('developer', 'developer')], default=('visitor', 'visitor'), max_length=100, verbose_name='User Type')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is Superuser')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('is_verify', models.BooleanField(default=False, verbose_name='Is Verify')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adderss')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City Name')),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='Zipcode')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Joined Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Profile')),
            ],
        ),
    ]
